export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const GET_VIDEOGAMES_BY_ID = 'GET_VIDEOGAMES_BY_ID';
export const GET_VIDEOGAMES_BY_NAME = 'GET_VIDEOGAMES_BY_NAME';
export const GET_GENRES = 'GET_GENRES';
export const SEARCH = 'SEARCH';
export const GET_PLATFORMS = 'GET_PLATFORMS';